/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TimelineEvent = IDL.Record({
  'date' : IDL.Text,
  'event' : IDL.Text,
  'location' : IDL.Text,
});
export const Shipment = IDL.Record({
  'weight' : IDL.Text,
  'status' : IDL.Text,
  'trackingNumber' : IDL.Text,
  'serviceType' : IDL.Text,
  'destination' : IDL.Text,
  'recipientPhone' : IDL.Text,
  'createdAt' : Time,
  'origin' : IDL.Text,
  'estimatedDelivery' : IDL.Text,
  'handlingFee' : IDL.Text,
  'shippingCost' : IDL.Text,
  'senderName' : IDL.Text,
  'recipientAddress' : IDL.Text,
  'recipientName' : IDL.Text,
  'senderAddress' : IDL.Text,
  'timeline' : IDL.Vec(TimelineEvent),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TimelineEventInput = IDL.Record({
  'date' : IDL.Text,
  'event' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [], []),
  'createShipment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteShipment' : IDL.Func([IDL.Text], [], []),
  'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getShipment' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
  'getShipmentsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Shipment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFirstAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateShipmentStatus' : IDL.Func(
      [IDL.Text, IDL.Text, TimelineEventInput],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TimelineEvent = IDL.Record({
    'date' : IDL.Text,
    'event' : IDL.Text,
    'location' : IDL.Text,
  });
  const Shipment = IDL.Record({
    'weight' : IDL.Text,
    'status' : IDL.Text,
    'trackingNumber' : IDL.Text,
    'serviceType' : IDL.Text,
    'destination' : IDL.Text,
    'recipientPhone' : IDL.Text,
    'createdAt' : Time,
    'origin' : IDL.Text,
    'estimatedDelivery' : IDL.Text,
    'handlingFee' : IDL.Text,
    'shippingCost' : IDL.Text,
    'senderName' : IDL.Text,
    'recipientAddress' : IDL.Text,
    'recipientName' : IDL.Text,
    'senderAddress' : IDL.Text,
    'timeline' : IDL.Vec(TimelineEvent),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TimelineEventInput = IDL.Record({
    'date' : IDL.Text,
    'event' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [], []),
    'createShipment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteShipment' : IDL.Func([IDL.Text], [], []),
    'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getShipment' : IDL.Func([IDL.Text], [IDL.Opt(Shipment)], ['query']),
    'getShipmentsByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Shipment)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFirstAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateShipmentStatus' : IDL.Func(
        [IDL.Text, IDL.Text, TimelineEventInput],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };