/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Shipment {
  'weight' : string,
  'status' : string,
  'trackingNumber' : string,
  'serviceType' : string,
  'destination' : string,
  'recipientPhone' : string,
  'createdAt' : Time,
  'origin' : string,
  'estimatedDelivery' : string,
  'handlingFee' : string,
  'shippingCost' : string,
  'senderName' : string,
  'recipientAddress' : string,
  'recipientName' : string,
  'senderAddress' : string,
  'timeline' : Array<TimelineEvent>,
}
export type Time = bigint;
export interface TimelineEvent {
  'date' : string,
  'event' : string,
  'location' : string,
}
export interface TimelineEventInput {
  'date' : string,
  'event' : string,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimFirstAdmin' : ActorMethod<[], undefined>,
  'createShipment' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'deleteShipment' : ActorMethod<[string], undefined>,
  'getAllShipments' : ActorMethod<[], Array<Shipment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getShipment' : ActorMethod<[string], [] | [Shipment]>,
  'getShipmentsByStatus' : ActorMethod<[string], Array<Shipment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFirstAdminClaimed' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateShipmentStatus' : ActorMethod<
    [string, string, TimelineEventInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];